# This is a basic workflow to help you get started with Actions

name: JavaCI

on: [ push, pull_request ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 15.0.2 for x64
        uses: actions/setup-java@v1
        with:
          java-version: '15.0.2'
          architecture: x64
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify "-Dspring.profiles.active=ci"
